### ISSUE TITLE
Wind Factor Component version 4.2 is throwing error in Annual wind study template

### ISSUE THREAD

**Issue by asisnatha** [EnvironmentalSystemsLab/Eddy3D-Public#9]
I updated the template for annual wind analysis to 4.2ver and the simulation ran successfully. I could visualize the wind vectors for all directions. But when I am trying to run wind factor component  throws error as " Object reference not set to instance of the object". Kindly assist in solving this
![image](https://github.com/EnvironmentalSystemsLab/Eddy3D-Public/assets/41608759/e03bc3d1-43dc-42a7-ad3c-a058a8741fe6)

**Comment by kastnerp** [comment]
Could you please check if any input are `Null` and report back?

**Comment by asisnatha** [comment]
@kastnerp I had checked the script again thoroughly. The issue persists.

**Comment by asisnatha** [comment]
That would be great. @kastnerp , so for now the current version will not work with R8?

**Comment by kastnerp** [comment]
First off, I just published `v0.4.2.1` for Rhino 7. 
I manually tested some templates earlier, and it seems the Rhino 8 UI introduces breaking changes that relate to the cylindrical domain. The Box Domain seems to work, though. 

The unit tests all passed, so it likely has to do with how the UI interfaces with the component logic. I will have to investigate further.

**Comment by asisnatha** [comment]
Ok. Till then have to install Rhino 7 again. Will test in Rhino 7 and let you know if I encounter any issue!

**Comment by asisnatha** [comment]
Hi, Do we have any update for Rhino 8?

**Comment by Hemy17** [comment]
Hello! I'm sorry to disturb you. I'm running version 0.4.2.1 of the component in Rhino 7 and still encountering the same error. May I ask what the reason might be?

**Comment by kastnerp** [comment]
This should be fixed now. Will be uploading `v0.4.8.0` in a bit.
